### ISSUE TITLE
How to use usb-mount-notify.js ?

### ISSUE THREAD

**Issue by sboudouk** [skyderby/flysight_setup#1]
Hi, first thanks for sharing this. I Need to see the path of the plugged devices on Windows, and your usb-mount-notify.js seems to be exactly what i need.

Do you have any example on how and what do you need to use it ? Is this a listemer that don't need anything ?

This is absolutely not an issue but i'm new to github and coding in general and I don't know where to notice you/ask you this.

Thanks for future answers ! @skyksandr (Maybe you can help too).

**Comment by skyksandr** [comment]
Hi, this app is based on Electron (previously Atom shell). Are you making app on electron as well? or plain node js app?

**Comment by sboudouk** [comment]
@skyksandr : In a large way we're planning Electron app, yes. But actually i'm just building a script that detect that a device is connected, get it mountpoint, then i can access it and copy the USB content to HDD.

**Comment by skyksandr** [comment]
for Windows it will work only under the Electron, because it provides hookWindowMessage on mainWindow. There is no simple way to handle this events without an opened window.
So my advice is to make hello world Electron app. then extend it with:

```
app.on('ready', function() {
  ...
  var usb_mount_notify = require('./usb-mount-notify');
  usb_mount_notify.onDeviceChange(onDeviceChange, mainWindow);
}

function onDeviceChange(event_name, device_path) {
  // event_name - mount or unmount
  // device_path - 'E:\' for windows, '/Volumes/Something/' for mac

  // trigger an event on main window
  mainWindow.webContents.send(event_name, device_path);
}
```

**Comment by sboudouk** [comment]
Even if I don't need to trigger an event on main window ? If I just need to show Mountpoint on stdout it will not work ?

Anyway thanks for you answers i think i got the usage of the thing.

**Comment by skyksandr** [comment]
You'll need it for 

```
mainWindow.hookWindowMessage(
    Number.parseInt('0x0219'), // WM_DEVICECHANGE
    function(w_param, l_param_pointer) {
```

**Comment by sboudouk** [comment]
Thanks,you can close the issue.
